# Generated by Django 4.2.30 on 2026-05-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_roomtype_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
