# Generated by Django 4.2.30 on 2026-05-17 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_service_room_bed_type_rating_reservation_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.reservation'),
        ),
    ]
